# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions and https://github.com/actions/setup-node

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile # optional, --immutable
    - run: yarn run test

  e2e-test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x, 16.x]
      needs: [unit-test]
      steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn run test:e2e

